# Generated by Django 2.2.7 on 2019-12-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictive_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('predictivemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='predictive_model.PredictiveModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('predictive_model.predictivemodel',),
        ),
        migrations.CreateModel(
            name='Lasso',
            fields=[
                ('regression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regression.Regression')),
                ('alpha', models.FloatField()),
                ('fit_intercept', models.BooleanField()),
                ('normalize', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('regression.regression',),
        ),
        migrations.CreateModel(
            name='Linear',
            fields=[
                ('regression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regression.Regression')),
                ('fit_intercept', models.BooleanField()),
                ('normalize', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('regression.regression',),
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('regression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regression.Regression')),
                ('n_hidden_layers', models.PositiveIntegerField()),
                ('n_hidden_units', models.PositiveIntegerField()),
                ('activation', models.CharField(choices=[('sigmoid', 'sigmoid'), ('tanh', 'tanh'), ('relu', 'relu')], default='relu', max_length=8)),
                ('n_epochs', models.PositiveIntegerField()),
                ('dropout_rate', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('regression.regression',),
        ),
        migrations.CreateModel(
            name='RandomForest',
            fields=[
                ('regression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regression.Regression')),
                ('n_estimators', models.PositiveIntegerField()),
                ('max_features', models.CharField(choices=[('auto', 'auto'), ('sqrt', 'sqrt'), ('log2', 'log2')], default=None, max_length=5, null=True)),
                ('max_depth', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('regression.regression',),
        ),
        migrations.CreateModel(
            name='XGBoost',
            fields=[
                ('regression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regression.Regression')),
                ('max_depth', models.PositiveIntegerField()),
                ('n_estimators', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('regression.regression',),
        ),
    ]
