# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('config', jsonfield.fields.JSONField()),
                ('status', models.CharField(default='created', max_length=200)),
                ('result', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
