# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:25
from __future__ import unicode_literals

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('config', jsonfield.fields.JSONField()),
                ('error', models.CharField(default='', max_length=200)),
                ('status', models.CharField(
                    choices=[('created', 'Created'), ('completed', 'Completed'), ('error', 'Error'),
                             ('running', 'Running')], default='created', max_length=20)),
                ('result', jsonfield.fields.JSONField(default={})),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'),
                                                   ('nextActivity', 'Next activity')], max_length=20)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logs.Split')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
