# Generated by Django 2.0.3 on 2018-04-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logs.Split'),
        ),
    ]
