# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='classification', max_length=20),
            preserve_default=False,
        ),
    ]
