# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('error', 'Error'), ('running', 'Running')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], max_length=20),
        ),
    ]
