# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0002_auto_20180416_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')],
                                   max_length=20),
        ),
    ]
