# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20171127_2010'),
        ('jobs', '0003_auto_20171114_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='split',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='logs.Split'),
            preserve_default=False,
        ),
    ]
