# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0003_auto_20180423_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'),
                                            ('labelling', 'Labelling')], max_length=20),
        ),
    ]
