# Generated by Django 2.0.3 on 2018-03-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180326_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logs.Split'),
        ),
    ]
