# Generated by Django 2.0.3 on 2018-03-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180326_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='run',
        ),
    ]
