# Generated by Django 2.2.7 on 2019-12-25 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('split', '0001_initial'),
        ('predictive_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('shap', 'shap'), ('lime', 'lime'), ('anchor', 'anchor')], default='shap', max_length=7, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.Job')),
                ('predictive_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='predictive_model.PredictiveModel')),
                ('split', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='split.Split')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
