ignore:
  - "tests/test_*.py"
  - "**/tests/test_*.py"
  - "**/**/tests/test_*.py"
  - "./docs/**"
  - "./cache/**"
  - "./results/**"
  - "./db/**"
  - "./nirdizati_research/wsgi.py"
  - "./scripts/**"
  - "./src/jobs/management/commands/**.py"
#  TEMPORARY EXCLUSIONS
  - "src/runtime/**"
  - "pred_models/**"
