# Generated by Django 2.2.7 on 2019-12-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('split', '0001_initial'),
        ('encoding', '0001_initial'),
        ('labelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadedLog',
            fields=[
                ('cache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cache.Cache')),
                ('train_log_path', models.FilePathField(path='cache/loaded_log_cache/')),
                ('test_log_path', models.FilePathField(path='cache/loaded_log_cache/')),
                ('additional_columns_path', models.FilePathField(max_length=500, null=True, path='cache/loaded_log_cache/')),
                ('split', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='split.Split')),
            ],
            options={
                'abstract': False,
            },
            bases=('cache.cache',),
        ),
        migrations.CreateModel(
            name='LabelledLog',
            fields=[
                ('cache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cache.Cache')),
                ('train_log_path', models.FilePathField(path='cache/labeled_log_cache/')),
                ('test_log_path', models.FilePathField(path='cache/labeled_log_cache/')),
                ('encoding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='encoding.Encoding')),
                ('labelling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='labelling.Labelling')),
                ('split', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='split.Split')),
            ],
            options={
                'abstract': False,
            },
            bases=('cache.cache',),
        ),
    ]
