"""Python has no real constants, will still try my best"""

# Classification methods
KNN = 'knn'
RANDOM_FOREST = 'randomForest'
DECISION_TREE = 'decisionTree'
INCREMENTAL_NAIVE_BAYES = 'incrementalNaiveBayes'

# Regression methods
LINEAR = 'linear'
LASSO = 'lasso'
XGBOOST = 'xgboost'

# Clustering
KMEANS = 'kmeans'
NO_CLUSTER = 'noCluster'

# Job types
CLASSIFICATION = 'classification'
REGRESSION = 'regression'
LABELLING = 'labelling'
UPDATE = 'update'

# classification/regressor method confs
CLASSIFICATION_RANDOM_FOREST = '{}.{}'.format(CLASSIFICATION, RANDOM_FOREST)
CLASSIFICATION_KNN = '{}.{}'.format(CLASSIFICATION, KNN)
CLASSIFICATION_DECISION_TREE = '{}.{}'.format(CLASSIFICATION, DECISION_TREE)
CLASSIFICATION_INCREMENTAL_NAIVE_BAYES = '{}.{}'.format(CLASSIFICATION, INCREMENTAL_NAIVE_BAYES)
CLASSIFICATION_XGBOOST = '{}.{}'.format(CLASSIFICATION, XGBOOST)
REGRESSION_RANDOM_FOREST = '{}.{}'.format(REGRESSION, RANDOM_FOREST)
REGRESSION_LASSO = '{}.{}'.format(REGRESSION, LASSO)
REGRESSION_LINEAR = '{}.{}'.format(REGRESSION, LINEAR)
REGRESSION_XGBOOST = '{}.{}'.format(REGRESSION, XGBOOST)
UPDATE_INCREMENTAL_NAIVE_BAYES = '{}.{}'.format(UPDATE, INCREMENTAL_NAIVE_BAYES)

all_configs = [
               CLASSIFICATION_RANDOM_FOREST, CLASSIFICATION_KNN, CLASSIFICATION_DECISION_TREE, CLASSIFICATION_XGBOOST,
               CLASSIFICATION_INCREMENTAL_NAIVE_BAYES,
               REGRESSION_RANDOM_FOREST, REGRESSION_LASSO, REGRESSION_LINEAR, REGRESSION_XGBOOST,
               UPDATE_INCREMENTAL_NAIVE_BAYES
               ]
