"""Python has no real constants, will still try my best"""

# Classification methods
from skmultiflow.bayes import NaiveBayes
from skmultiflow.trees import HoeffdingTree, HAT

KNN = 'knn'
RANDOM_FOREST = 'randomForest'
DECISION_TREE = 'decisionTree'
NAIVE_BAYES = NaiveBayes().__class__.__name__
ADAPTIVE_TREE = HAT().__class__.__name__
HOEFFDING_TREE = HoeffdingTree().__class__.__name__

INCREMENTAL_NAIVE_BAYES = 'incremental' + NAIVE_BAYES
INCREMENTAL_ADAPTIVE_TREE = 'incremental' + ADAPTIVE_TREE
INCREMENTAL_HOEFFDING_TREE = 'incremental' + HOEFFDING_TREE

# Regression methods
LINEAR = 'linear'
LASSO = 'lasso'
XGBOOST = 'xgboost'

# Clustering
KMEANS = 'kmeans'
NO_CLUSTER = 'noCluster'

# Job types
CLASSIFICATION = 'classification'
REGRESSION = 'regression'
LABELLING = 'labelling'
UPDATE = 'update'

# classification/regressor method confs
CLASSIFICATION_RANDOM_FOREST = '{}.{}'.format(CLASSIFICATION, RANDOM_FOREST)
CLASSIFICATION_KNN = '{}.{}'.format(CLASSIFICATION, KNN)
CLASSIFICATION_DECISION_TREE = '{}.{}'.format(CLASSIFICATION, DECISION_TREE)
CLASSIFICATION_INCREMENTAL_NAIVE_BAYES = '{}.{}'.format(CLASSIFICATION, INCREMENTAL_NAIVE_BAYES)
CLASSIFICATION_INCREMENTAL_ADAPTIVE_TREE = '{}.{}'.format(CLASSIFICATION, INCREMENTAL_ADAPTIVE_TREE)
CLASSIFICATION_INCREMENTAL_HOEFFDING_TREE = '{}.{}'.format(CLASSIFICATION, INCREMENTAL_HOEFFDING_TREE)
CLASSIFICATION_XGBOOST = '{}.{}'.format(CLASSIFICATION, XGBOOST)
REGRESSION_RANDOM_FOREST = '{}.{}'.format(REGRESSION, RANDOM_FOREST)
REGRESSION_LASSO = '{}.{}'.format(REGRESSION, LASSO)
REGRESSION_LINEAR = '{}.{}'.format(REGRESSION, LINEAR)
REGRESSION_XGBOOST = '{}.{}'.format(REGRESSION, XGBOOST)
UPDATE_INCREMENTAL_NAIVE_BAYES = '{}.{}'.format(UPDATE, INCREMENTAL_NAIVE_BAYES)
UPDATE_INCREMENTAL_ADAPTIVE_TREE = '{}.{}'.format(UPDATE, INCREMENTAL_ADAPTIVE_TREE)
UPDATE_INCREMENTAL_HOEFFDING_TREE = '{}.{}'.format(UPDATE, INCREMENTAL_HOEFFDING_TREE)

all_configs = [
               CLASSIFICATION_RANDOM_FOREST, CLASSIFICATION_KNN, CLASSIFICATION_DECISION_TREE, CLASSIFICATION_XGBOOST,
               CLASSIFICATION_INCREMENTAL_NAIVE_BAYES, CLASSIFICATION_INCREMENTAL_ADAPTIVE_TREE, CLASSIFICATION_INCREMENTAL_HOEFFDING_TREE,
               REGRESSION_RANDOM_FOREST, REGRESSION_LASSO, REGRESSION_LINEAR, REGRESSION_XGBOOST,
               UPDATE_INCREMENTAL_NAIVE_BAYES, UPDATE_INCREMENTAL_ADAPTIVE_TREE, UPDATE_INCREMENTAL_HOEFFDING_TREE
               ]
