# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 15:38
from __future__ import unicode_literals

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.CharField(choices=[('kmeans', 'kmeans'), ('noCluster', 'noCluster')], default='noCluster',
                                  max_length=20)),
                ('model_path', models.CharField(default='error', max_length=200)),
                ('clusterer_path', models.CharField(blank=True, max_length=200, null=True)),
                ('predtype', models.CharField(
                    choices=[('classification', 'Classification'), ('regression', 'Regression'),
                             ('labelling', 'Labelling'), ('update', 'Update')], default='Classification',
                    max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PredModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'),
                                                   ('labelling', 'Labelling'), ('update', 'Update')], max_length=20)),
                ('config', jsonfield.fields.JSONField(default={})),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                          related_name='log', to='logs.Log')),
                ('split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            related_name='split', to='pred_models.ModelSplit')),
            ],
        ),
    ]
