# Generated by Django 2.2.7 on 2019-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.FilePathField(path='cache/model_cache/')),
                ('predictive_model', models.CharField(choices=[('classification', 'classification'), ('regression', 'regression'), ('time_series_prediction', 'time_series_prediction')], max_length=23)),
                ('prediction_method', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
