# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0003_auto_20180216_1045'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', jsonfield.fields.JSONField(default={})),
                ('elapsed_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.IntegerField(default=0)),
                ('date', models.DateField(default=None)),
                ('amount_req', models.IntegerField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace_log', to='logs.Log')),
                ('model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace_model', to='training.PredModels')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace', to='replayer.Trace'),
        ),
    ]
