# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
