# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replayer', '0003_trace_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='trace',
            name='amount_req',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='trace_id',
        ),
        migrations.AddField(
            model_name='trace',
            name='config',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='config',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='trace',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trace_log', to='replayer.Log'),
        ),
    ]
