# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('replayer', '0004_auto_20180307_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='log',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='trace',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
