# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replayer', '0005_auto_20180307_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='config',
        ),
        migrations.RemoveField(
            model_name='log',
            name='config',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='config',
        ),
    ]
