# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replayer', '0007_auto_20180308_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='elapsed_time',
        ),
    ]
