# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('runtime', '0001_initial'), ('runtime', '0002_replayer'), ('runtime', '0003_auto_20180507_0756'), ('runtime', '0004_auto_20180523_1015'), ('runtime', '0005_auto_20180529_1450'), ('runtime', '0006_auto_20180529_1527'), ('runtime', '0007_xtrace_real_log'), ('runtime', '0008_auto_20180530_1301'), ('runtime', '0009_xtrace_completed')]

    initial = True

    dependencies = [
        ('predModels', '0001_initial'),
        ('logs', '0002_log_properties'),
        ('predModels', '0005_auto_20180523_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='XEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
                ('class_results', jsonfield.fields.JSONField(default={})),
                ('xlog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='xlog', to='runtime.XLog')),
                ('class_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_trace_model', to='predModels.PredModels')),
                ('reg_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_trace_model', to='predModels.PredModels')),
                ('reg_results', jsonfield.fields.JSONField(default={})),
                ('real_log', models.IntegerField(default=2)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='xevent',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='xtrace', to='runtime.XTrace'),
        ),
        migrations.CreateModel(
            name='DemoReplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='xlog',
            name='real_log',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_log', to='logs.Log'),
            preserve_default=False,
        ),
    ]
