# Generated by Django 2.0.3 on 2018-04-17 12:13

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('predModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(default='', max_length=500, null=True)),
                ('results', jsonfield.fields.JSONField(default={})),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='xlog',
                                          to='runtime.XLog')),
                ('model',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                   related_name='trace_model', to='predModels.PredModels')),
            ],
        ),
        migrations.AddField(
            model_name='xevent',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='xtrace', to='runtime.XTrace'),
        ),
    ]
