# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_properties'),
        ('predModels', '0005_auto_20180523_1015'),
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoReplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='xtrace',
            old_name='results',
            new_name='class_actual',
        ),
        migrations.RenameField(
            model_name='xtrace',
            old_name='log',
            new_name='xlog',
        ),
        migrations.RemoveField(
            model_name='xtrace',
            name='model',
        ),
        migrations.AddField(
            model_name='xevent',
            name='xid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='xlog',
            name='real_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_log', to='logs.Log'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xtrace',
            name='class_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_trace_model', to='predModels.PredModels'),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='class_results',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='error',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='first_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='last_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='n_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='real_log',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xtrace',
            name='reg_actual',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='reg_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_trace_model', to='predModels.PredModels'),
        ),
        migrations.AddField(
            model_name='xtrace',
            name='reg_results',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
