# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0002_replayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replayer',
            new_name='DemoReplayer',
        ),
    ]
