# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0002_auto_20180620_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtrace',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
