# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_xtrace_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtrace',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
