# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0004_auto_20180523_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtrace',
            name='class_results',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='xtrace',
            name='reg_results',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
