# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_properties'),
        ('runtime', '0005_auto_20180529_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xtrace',
            old_name='log',
            new_name='xlog',
        ),
        migrations.AddField(
            model_name='xlog',
            name='real_log',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_log', to='logs.Log'),
            preserve_default=False,
        ),
    ]
