# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0006_auto_20180529_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtrace',
            name='real_log',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
