# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 13:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0007_xtrace_real_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtrace',
            name='class_results',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='xtrace',
            name='reg_results',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
