# Generated by Django 2.2.7 on 2019-12-25 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encoding', models.CharField(choices=[('label_encoder', 'label_encoder'), ('one_hot', 'one_hot')], default='label_encoder', max_length=14)),
                ('value_encoding', models.CharField(choices=[('simpleIndex', 'simpleIndex'), ('boolean', 'boolean'), ('frequency', 'frequency'), ('complex', 'complex'), ('lastPayload', 'lastPayload')], default='simpleIndex', max_length=12)),
                ('add_elapsed_time', models.BooleanField(default=False)),
                ('add_remaining_time', models.BooleanField(default=False)),
                ('add_executed_events', models.BooleanField(default=False)),
                ('add_resources_used', models.BooleanField(default=False)),
                ('add_new_traces', models.BooleanField(default=False)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('prefix_length', models.PositiveIntegerField()),
                ('padding', models.BooleanField(default=False)),
                ('task_generation_type', models.CharField(choices=[('up_to', 'up_to'), ('only', 'only_this'), ('all_in_one', 'all_in_one')], default='only_this', max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
