# Generated by Django 2.2.7 on 2019-12-25 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'single'), ('double', 'double')], default='single', max_length=7)),
                ('test_size', models.FloatField(blank=True, default=0.2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('splitting_method', models.CharField(choices=[('sequential', 'sequential'), ('temporal', 'temporal'), ('random', 'random'), ('strict_temporal', 'strict_temporal')], default='sequential', max_length=16)),
                ('additional_columns', models.FilePathField(blank=True, max_length=500, null=True, path='cache/loaded_log_cache/')),
                ('original_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_log', to='logs.Log')),
                ('test_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_log', to='logs.Log')),
                ('train_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_log', to='logs.Log')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
