# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', jsonfield.fields.JSONField(default={})),
                ('original_log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logs.Log')),
            ],
        ),
    ]
