# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('single', 'Double')], default='single', max_length=20),
        ),
    ]
