# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='test_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_log', to='logs.Log'),
        ),
        migrations.AddField(
            model_name='split',
            name='training_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_log', to='logs.Log'),
        ),
        migrations.AlterField(
            model_name='split',
            name='original_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_log', to='logs.Log'),
        ),
        migrations.AlterField(
            model_name='split',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=20),
        ),
    ]
