# Generated by Django 2.0.3 on 2018-04-16 12:11

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('logs', '0002_log_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'),
                                                   ('nextActivity', 'Next activity')], default='single',
                                          max_length=20)),
                ('model_path', models.CharField(default='error', max_length=200)),
                ('estimator_path', models.CharField(blank=True, max_length=200, null=True)),
                ('predtype', models.CharField(
                    choices=[('classification', 'Classification'), ('regression', 'Regression'),
                             ('nextActivity', 'Next activity')], default='Classification', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PredModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'),
                                                   ('nextActivity', 'Next activity')], max_length=20)),
                ('config', jsonfield.fields.JSONField(default={})),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                          related_name='log', to='logs.Log')),
                ('split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            related_name='split', to='predModels.ModelSplit')),
            ],
        ),
    ]
