# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('predModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsplit',
            name='predtype',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')],
                                   default='Classification', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelsplit',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')],
                                   default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='predmodels',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')],
                                   max_length=20),
        ),
    ]
