# Generated by Django 2.0.3 on 2018-04-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmodels',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='split', to='predModels.ModelSplit'),
        ),
    ]
