# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('predModels', '0002_auto_20180423_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsplit',
            name='type',
            field=models.CharField(choices=[('kmeans', 'kmeans'), ('noCluster', 'noCluster')], default='noCluster',
                                   max_length=20),
        ),
    ]
