# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('predModels', '0003_auto_20180424_0859'),
        ('predModels', '0003_auto_20180426_0945'),
    ]

    operations = [
    ]
