# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('predModels', '0004_merge_20180507_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsplit',
            name='type',
            field=models.CharField(choices=[('kmeans', 'kmeans'), ('noCluster', 'noCluster')], default='noCluster',
                                   max_length=20),
        ),
    ]
