# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predModels', '0005_auto_20180523_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsplit',
            name='predtype',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('labelling', 'Labelling'), ('update', 'Update')], default='Classification', max_length=20),
        ),
        migrations.AlterField(
            model_name='predmodels',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('labelling', 'Labelling'), ('update', 'Update')], max_length=20),
        ),
    ]
