# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predModels', '0006_auto_20180821_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsplit',
            old_name='estimator_path',
            new_name='clusterer_path',
        ),
    ]
