# Generated by Django 2.2.7 on 2019-12-25 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('next_activity', 'next_activity'), ('attribute_string', 'attribute_string'), ('attribute_number', 'attribute_number'), ('remaining_time', 'remaining_time'), ('duration', 'duration'), ('no_label', 'no_label')], default='attribute_string', max_length=17, null=True)),
                ('attribute_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('threshold_type', models.CharField(blank=True, choices=[('threshold_mean', 'threshold_mean'), ('threshold_custom', 'threshold_custom'), ('none', 'none')], default='none', max_length=17, null=True)),
                ('threshold', models.IntegerField(blank=True, default=0, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
