# Generated by Django 2.2.7 on 2019-12-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparameterOptimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_method', models.CharField(choices=[('hyperopt', 'hyperopt'), ('none', 'none')], default='hyperopt', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HyperOpt',
            fields=[
                ('hyperparameteroptimization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hyperparameter_optimization.HyperparameterOptimization')),
                ('max_evaluations', models.PositiveIntegerField()),
                ('performance_metric', models.CharField(choices=[('rmse', 'rmse'), ('mae', 'mae'), ('rscore', 'rscore'), ('acc', 'acc'), ('f1score', 'f1score'), ('auc', 'auc'), ('precision', 'precision'), ('recall', 'recall'), ('true_positive', 'true_positive'), ('true_negative', 'true_negative'), ('false_positive', 'false_positive'), ('false_negative', 'false_negative'), ('mape', 'mape')], default='acc', max_length=15)),
                ('algorithm_type', models.CharField(choices=[('random_search', 'random_search'), ('tpe', 'tpe')], default='tpe', max_length=14)),
            ],
            options={
                'abstract': False,
            },
            bases=('hyperparameter_optimization.hyperparameteroptimization',),
        ),
    ]
