# Generated by Django 2.0.3 on 2018-03-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], max_length=20)),
                ('prefix_length', models.IntegerField(default=1)),
                ('encoding', models.CharField(choices=[('simpleIndex', 'simpleIndex'), ('boolean', 'boolean'), ('frequency', 'frequency'), ('complex', 'complex'), ('lastPayload', 'lastPayload')], default='simpleIndex', max_length=20)),
                ('method', models.CharField(choices=[('knn', 'knn'), ('randomForest', 'randomForest'), ('decisionTree', 'decisionTree'), ('linear', 'linear'), ('lasso', 'lasso')], default='linear', max_length=20)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='logs.Log')),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], default='single', max_length=20)),
                ('model_path', models.CharField(default='error', max_length=200)),
                ('kmean_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='predmodels',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='training.Split'),
        ),
    ]
