# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], max_length=20)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='logs.Log')),
            ],
        ),
    ]
