# Generated by Django 2.0.3 on 2018-03-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='predtype',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], default='Classification', max_length=20),
        ),
    ]
