# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmodels',
            name='encoding',
            field=models.CharField(choices=[('simpleIndex', 'simpleIndex'), ('boolean', 'boolean'), ('frequency', 'frequency'), ('complex', 'complex'), ('lastPayload', 'lastPayload')], default='simpleIndex', max_length=20),
        ),
        migrations.AddField(
            model_name='predmodels',
            name='method',
            field=models.CharField(choices=[('knn', 'knn'), ('randomForest', 'randomForest'), ('decisionTree', 'decisionTree'), ('linear', 'linear'), ('lasso', 'lasso')], default='linear', max_length=20),
        ),
        migrations.AddField(
            model_name='predmodels',
            name='prefix_length',
            field=models.IntegerField(default=1),
        ),
    ]
