# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20180215_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nextActivity', 'Next activity')], default='single', max_length=20)),
                ('model_path', models.CharField(default='error', max_length=200)),
                ('kmean_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='predmodels',
            name='path',
        ),
        migrations.AddField(
            model_name='predmodels',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='training.Split'),
        ),
    ]
