# Generated by Django 2.2.7 on 2019-12-25 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('split', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('clustering', '0001_initial'),
        ('predictive_model', '0001_initial'),
        ('encoding', '0001_initial'),
        ('hyperparameter_optimization', '0001_initial'),
        ('labelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(default='', max_length=500)),
                ('status', models.CharField(choices=[('created', 'created'), ('completed', 'completed'), ('error', 'error'), ('running', 'running')], default='created', max_length=10)),
                ('type', models.CharField(choices=[('prediction', 'prediction'), ('labelling', 'labelling'), ('update', 'update'), ('runtime', 'runtime'), ('replay', 'replay'), ('replay_predict', 'replay_predict')], default='prediction', max_length=15)),
                ('create_models', models.BooleanField(default=False)),
                ('case_id', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('event_number', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('gold_value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('clustering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clustering.Clustering')),
                ('encoding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='encoding.Encoding')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evaluation.Evaluation')),
                ('hyperparameter_optimizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hyperparameter_optimization.HyperparameterOptimization')),
                ('incremental_train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_model', to='jobs.Job')),
                ('labelling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='labelling.Labelling')),
                ('parent_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replay_job', to='jobs.Job')),
                ('predictive_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='predictive_model.PredictiveModel')),
                ('split', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='split.Split')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
